[package]
name = "asciii"
version = "3.0.0-alpha0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]


[dependencies]

#csv = "*"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*"
regex = "*"
slug = "*"
term = "*"
terminal_size = "0.1.1"
prettytable-rs = "*"
currency = {git="https://github.com/hoodie/rust-lang-currency"}
#currency = {path="../currency"}
lazy_static = "*"
git2 = "*"
maplit = "*"
tempdir = "*"
open = "*"

enum_derive = "*"
custom_derive = "*"

clippy = {version = "*", optional = true}

[dependencies.clap]
version = "2"
features= ["yaml"]

[features]
default = []
lints = ["clippy"]

[[bin]]
test = false
doc = false
name = "asciii"
