[package]
name = "asciii"
version = "2.9.9-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

build = "build.rs"


[dependencies]

log = "0.3"
env_logger = "0.3"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "0.2"
regex = "0.1"
lazy_static = "0.2"
maplit = "0.1"
clap = {version = "2"}
enum_derive = "0.1"
custom_derive = "0.1"
currency = {git="https://github.com/hoodie/rust-lang-currency"}
#currency = "0.4"
open = "1.1"

slug = "0.1"
tempdir = "0.3"

term = "0.4"
terminal_size = "0.1.1" # TODO consider termsize or others
prettytable-rs = "0.6"

# feature: lints
clippy = {version = "*", optional = true}

# feature: document_export
handlebars = {version = "*", optional = true}
serde = { version = "*", optional = true }
serde_json = { version = "^0.7.0", optional = true }
rustc-serialize = {version = "*", optional = true }

# feature: git_statuses
git2 = {version = "*", default-features= false, optional = true}

# planned optional features: termprint, term resize, xdg-open, web server :D

[features]
default = ["git_statuses"]
document_export = ["handlebars","serde","serde_json","rustc-serialize"]
debug_config = []
git_statuses = ["git2"]
nightly = []
lints = ["clippy"]

[[bin]]
test = false
doc = false
name = "asciii"

