[package]
name = "ascii_invoicer"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
doc = false # bin is documented

[dependencies]

#csv = "*"
yaml-rust = "*"
chrono = "*"
regex = "*"
slug = "*"
clap = "*"
term = "*"
prettytable-rs = "*"
pad = "*"

[dev-dependencies]
tempdir = "*"
#speculate = "*"
#clippy = "*"

[[bin]]
name = "ascii"
