[package]
name = "asciii"
version = "3.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
license = "MIT/Apache-2.0"

build = true

[dependencies]
log = "0.3"
env_logger = "0.4" # default feature requires regex
yaml-rust = {git = "https://github.com/chyh1990/yaml-rust/"}
chrono = "0.4"
regex = "0.2"
lazy_static = "0.2"
maplit = "0.1"
clap = "2"
enum_derive = "0.1"
custom_derive = "0.1"
open = "1.1"
error-chain = "0.10"
crowbook-intl-runtime = "0.1"
rustyline = {version = "1.0.0", optional = true }

bill = {version= "0.2", features=["serialization"]}
icalendar = "0.3"

slug = "0.1"
tempdir = "0.3"
semver = "0.7"
term_size = "0.3"

term = "0.4"
prettytable-rs = { version = "0.6", default-features= false}

# feature: document_export
handlebars = {version = "0.28", optional = true}

serde         = {version = "1.0", optional = true}
serde_json    = {version = "1.0", optional = true}
serde_yaml    = {version = "0.7", optional = true}
serde_derive  = {version = "1.0", optional = true}
ordered-float = {version = "0.5", optional = true}
num-traits    = {version = "0.1", optional = true}
toml          = "0.4"

# feature: git_statuses
git2 = {version = "0.6", default-features= false, optional = true}

[dev-dependencies]
pretty_assertions = "*"

[features]
default = ["document_export", "git_statuses", "shell", "serialization", "deserialization", "version_string"]
document_export = ["handlebars", "serialization"]
serde_base = ["serde", "serde_derive"]
serialization = ["serde_base", "serde_json"]
deserialization = ["serde_base","serde_yaml", "ordered-float", "num-traits"]
git_statuses = ["git2"]
shell = ["rustyline"]
version_string = []
localize = []
nightly = []

[profile.release]
lto = true

[[bin]]
test = false
doc = false
name = "asciii"

[build-dependencies]
chrono = "0.4"
crowbook-intl = "0.2.0"
