[package]
name = "asciii"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]


[dependencies]

#csv = "*"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*"
regex = "*"
slug = "*"
term = "*"
terminal_size = "0.1.1"
prettytable-rs = "*"
#currency = {git="https://github.com/hoodie/rust-lang-currency"}
currency = {path="../currency"}
lazy_static = "*"
maplit = "*"
tempdir = "*"

clippy = {version = "~0.0.23", optional = true}

[dependencies.clap]
version = "2"
features= ["yaml"]

[dependencies.git2]
version = "*"
optional = true

[features]
default = ["git"]
lints = ["clippy"]
git = ["git2"]
