[package]
name = "ascii_invoicer"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]

csv = "*"
yaml-rust = "*"
chrono = "*"
regex = "*"
slug = "*"

[dev-dependencies]
tempdir = "*"
#speculate = "*"
#clippy = "*"
