[package]
name = "asciii"
version = "3.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
license = "MIT/Apache-2.0"

build = "build.rs"

[dependencies]

log = "0.3"
env_logger = { version = "0.3"} # default feature requires regex
yaml-rust = {version = "0.3", features = ["preserve_order"]}
chrono = "0.2"
regex = "0.1"
lazy_static = "0.2"
maplit = "0.1"
clap = "2"
enum_derive = "0.1"
custom_derive = "0.1"
open = "1.1"
ordered-float = "0.3"
error-chain = "0.6"
rustyline = {git="https://github.com/kkawakam/rustyline/", rev="1ae47dc", optional = true }

bill = {git="https://github.com/hoodie/bill-rs"}
icalendar = {git="https://github.com/hoodie/icalendar-rs"}
#icalendar = {path="../icalendar-rs"}

slug = "0.1"
tempdir = "0.3"
semver = "0.5"
term_size = "0.2"

term = "0.4"
prettytable-rs = { version = "0.6", default-features= false}

# feature: lints
#herbie-lint = {version = "*", optional = true}

# feature: document_export
handlebars = {version = "*", optional = true}
rustc-serialize = {version = "*", optional = true}

# feature: git_statuses
git2 = {version = "*", default-features= false, optional = true}

# planned optional features: termprint, term resize, xdg-open, web server :D

[features]
default = ["document_export", "git_statuses"]
document_export = ["rustc-serialize", "handlebars"]
git_statuses = ["git2"]
shell = ["rustyline"]
nightly = []

[profile.release]
lto = true

[[bin]]
test = false
doc = false
name = "asciii"

[build-dependencies]
clap = "2"
