[package]
name = "asciii"
version = "2.9.9-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

#build = "build.rs"


[dependencies]

log = "*" #"0.3"
num = "*" #"0.1"
env_logger = "*" #"0.3"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*" #"0.2"
regex = "*" #"0.1"
lazy_static = "*" #"0.2"
maplit = "*" #"0.1"
clap = {version = "2"}
enum_derive = "*" #"0.1"
custom_derive = "*" #"0.1"
open = "*" #"1.1"
ordered-float = "*"

claude = {git="https://github.com/hoodie/claude-rs"}
bill = {git="https://github.com/hoodie/bill-rs"}

slug = "*" #"0.1"
tempdir = "*" #"0.3"

term = "0.4"
terminal_size = "0.1.1" # TODO consider termsize or others
#prettytable-rs = "0.6"
prettytable-rs = { git = "https://github.com/hoodie/prettytable-rs", branch = "bug/encode_tostring" }

# feature: lints
clippy = {version = "*", optional = true}

# feature: document_export
handlebars = {version = "*", optional = true}
rustc-serialize = {version = "*", optional = true}

# feature: git_statuses
git2 = {version = "*", default-features= false, optional = true}

# planned optional features: termprint, term resize, xdg-open, web server :D

[features]
default = []
document_export = ["rustc-serialize", "handlebars"]
debug_config = []
git_statuses = ["git2"]
nightly = []
lints = ["clippy"]

[profile.release]
lto = true

[[bin]]
test = false
doc = false
name = "asciii"

