[package]
name = "asciii"
version = "2.9.9-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]


[dependencies]

log = "*"
env_logger = "*"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*"
regex = "*"
lazy_static = "*"
maplit = "*"
clap = "2"
enum_derive = "*"
custom_derive = "*"
clippy = {version = "*", optional = true}

slug = "*"
tempdir = "*"

term = "*"
terminal_size = "0.1.1" # TODO consider termsize or others
prettytable-rs = "*"

currency = {git="https://github.com/hoodie/rust-lang-currency"}
git2 = {version = "*", default-features=false}
open = "*"

[features]
default = ["document_export"]
document_export = []
debug_config = []
nightly = []
lints = ["clippy"]

[[bin]]
test = false
doc = false
name = "asciii"

# planned optional features: git, pdf output, termprint, term resize, xdg-open, web server :D
