[package]
name = "ascii_invoicer"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]

#csv = "*"
yaml-rust = "*" #{git="https://github.com/chyh1990/yaml-rust/", branch="alias"}
chrono = "*"
regex = "*"
slug = "*"
term = "*"
prettytable-rs = "*"
currency = {git="https://github.com/hoodie/rust-lang-currency"}
lazy_static = "*"
maplit = "*"
tempdir = "*"
git2    = "*"

clippy = {version = "~0.0.23", optional = true}

[dependencies.clap]
version = "2"
features= ["yaml"]

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "asciii"
doc = false
