[package]
name = "asciii"
version = "3.0.0-alpha"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]


[dependencies]

#csv = "*"
log = "*"
env_logger = "*"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*"
regex = "*"
slug = "*"
term = "*"
terminal_size = "0.1.1" # TODO consider termsize or others
prettytable-rs = "*"
currency = {git="https://github.com/hoodie/rust-lang-currency"}
#currency = {path="../currency"}
lazy_static = "*"
git2 = "*"
maplit = "*"
tempdir = "*"
open = "*"

enum_derive = "*"
custom_derive = "*"

clippy = {version = "*", optional = true}
clap = { version = "2", features= ["yaml"]}

[features]
default = []
debug_config = []
nightly = []
lints = ["clippy"]

[[bin]]
test = false
doc = false
name = "asciii"

# planned optional features: git, pdf output, termprint, term resize, xdg-open, web server :D
