[package]
name = "asciii"
version = "2.9.9-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

#build = "build.rs"


[dependencies]

log = "*" #"0.3"
env_logger = { version = "0.3", default-features=false} # default feature requires regex
#yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="bug/emitter"}
yaml-rust = {path="../yaml-rust"}
chrono = "*" #"0.2"
regex = "*" #"0.1"
lazy_static = "*" #"0.2"
maplit = "*" #"0.1"
clap = "*"
enum_derive = "*" #"0.1"
custom_derive = "*" #"0.1"
open = "*" #"1.1"
ordered-float = "*"
error-chain = "0.5"

claude = {git="https://github.com/hoodie/claude-rs", features=["tojson"]}
#bill = {git="https://github.com/hoodie/bill-rs"}
bill = {path="../bill-rs"}

slug = "*" #"0.1"
tempdir = "*" #"0.3"

term = "0.4"
prettytable-rs = { version = "0.6", default-features=false}

# feature: lints
clippy = {version = "*", optional = true}
#herbie-lint = {version = "*", optional = true}

# feature: document_export
#handlebars = {version = "*", optional = true}
handlebars = {git = "https://github.com/sunng87/handlebars-rust", optional = true}
rustc-serialize = {version = "*", optional = true}

# feature: git_statuses
git2 = {version = "*", default-features= false, optional = true}

# planned optional features: termprint, term resize, xdg-open, web server :D

[features]
default = ["document_export", "git_statuses"]
document_export = ["rustc-serialize", "handlebars"]
git_statuses = ["git2"]
nightly = []
lints = ["clippy"]

[profile.release]
lto = true

[[bin]]
test = false
doc = false
name = "asciii"
