[package]
name = "asciii"
version = "2.9.9-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

build = "build.rs"


[dependencies]

log = "*"
env_logger = "*"
yaml-rust = {git="https://github.com/hoodie/yaml-rust", branch="feature/to_string"}
chrono = "*"
regex = "*"
lazy_static = "*"
maplit = "*"
clap = "2"
enum_derive = "*"
custom_derive = "*"
clippy = {version = "*", optional = true}
currency = {git="https://github.com/hoodie/rust-lang-currency"}
open = "*"

slug = "*"
tempdir = "*"

term = "*"
terminal_size = "0.1.1" # TODO consider termsize or others
prettytable-rs = "*"

# feature: document_export
handlebars = {version = "*", optional = true}
serde_json = { version = "^0.7.0", optional = true }

# feature: git_statuses
git2 = {version = "*", default-features= false, optional = true}

# planned optional features: termprint, term resize, xdg-open, web server :D

[features]
default = ["git_statuses"]
document_export = ["handlebars","serde_json"]
debug_config = []
git_statuses = ["git2"]
nightly = []
lints = ["clippy"]

[[bin]]
test = false
doc = false
name = "asciii"

