[package]
name = "ascii_invoicer"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]

#csv = "*"
yaml-rust = "*"
chrono = "*"
regex = "*"
slug = "*"
clap = "*"
term = "*"
prettytable-rs = "*"
lazy_static = "*"
itertools = "*"
maplit = "*"
tempdir = "*"
git2    = "*"

clippy = {version = "~0.0.23", optional = true}

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "asciii"
doc = false
