---
user:
  name: #"The Unnamed Manager"
  editor: #"vim -O"

path: "~"
output_path: "."
list:
  colors:    false
  verbose:   false
  sort:      index
  gitstatus: false

  extra_details: #[OurBad, Caterers] # see asciii list --computed for all options

dirs:
  storage: asciii_projects
  working: working
  archive: archive
  templates: templates

template: default # default template

## CAREFUL HERE BREAK everything below here will not be copied over
extensions:
  project_file: yml
  project_template: tyml
  output_file: tex
  output_template: tex.hbs

convert:
  tool: pdflatex
  output_extension: pdf
  trash_extensions: [aux,log]
  default_template: document

#log_file: ~/.ascii_log # unimplemented
#calendar_file: invoicer.ics #unimplemented

defaults:
  tax: 0.19
  canceled: false
  salary: 8.0
  lang: de

currency: "€"

gender_matches:
  mr: male
  ms: female
  mrs: female
  herr: male
  frau: female
  professor: male
  professorin: female

lang_addressing:
  de:
    male: Sehr geehrter
    female: Sehr geehrte
  en:
    male: Dear
    female: Dear
...
