---
manager_name: #"The Unnamed Manager"
editor:       #"vim -O"

path: "~"
output_path: "."
list:
  colors:    false
  verbose:   false
  sort:      index
  gitstatus: false

dirs:
  storage: projects
  working: working
  archive: archive
  templates: templates

template: default # default template

## CAREFUL HERE
project_file_extension: .yml
latex:    pdflatex
#log_file: ~/.ascii_log # unimplemented
#calendar_file: invoicer.ics #unimplemented

defaults:
  tax: 0.19
  canceled: false
  salary: 8.0
  lang: de

currency: "€"

gender_matches:
  herr: male
  frau: female
  professor: male
  professorin: female

lang_addressing:
  de:
    male: Sehr geehrter
    female: Sehr geehrte
  en:
    male: Dear
    female: Dear
...
